name: Audit & Deploy

on:
  push:
    branches: [main]
    tags:
      - 'v*'

env:
  GO_VERSION: '1.20'

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Verify dependencies
      run: go mod verify

    - name: Build
      run: go build -o main cmd/main.go

    - name: Run go vet
      run: go vet ./...

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Run staticcheck
      run: staticcheck ./...

    - name: Run lint
      uses: golangci/golangci-lint-action@v3.4.0
      with:
        version: latest
        # skip cache because of flaky behaviors
        skip-build-cache: true
        skip-pkg-cache: true
    
    - name: Run tests
      run: go test -race -vet=off ./...

  deploy:
    runs-on: ubuntu-latest
    needs: audit
    if: |
      startsWith(github.ref, 'refs/tags') && contains(github.event.head_commit.message, '[deploy]')
    steps:
      - name: Extract Version
        id: version_step
        run: |
          echo "##[set-output name=version;]VERSION=${GITHUB_REF#refs/tags/v}"

      - name: Set version as environment variable
        run: echo "DOCKER_IMAGE_VERSION=${{ steps.version_step.outputs.version }}" >> $GITHUB_ENV

      # multiplatform image creation
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # advanced image creation
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            amnrah/fum-cloud-notification-report-2023:${{ env.DOCKER_IMAGE_VERSION }}
            amnrah/fum-cloud-notification-report-2023:latest
          build-args: |
            VERSION=${{ steps.version_step.outputs.version }}
